# Generated by Django 5.1.1 on 2024-09-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('distance', 'Distance'), ('duration', 'Duration'), ('calories', 'Calories')], max_length=50)),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('weightlifting', 'Weight Lifting')], max_length=50)),
                ('target', models.FloatField(verbose_name='your target in numbers')),
                ('time_period', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('all', 'All Time')], default='all', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
