# Generated by Django 5.1.1 on 2024-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time_period',
            field=models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('all', 'All Time')], max_length=50),
        ),
    ]
